### ISSUE TITLE
Getting syntax error while uglifying plugin 

### ISSUE THREAD

**Issue by rdandnayak** [wouter-vdb/retrying-promise#1]
When i tried uglifying the plugin with browserify and uglifyify

 bundler.transform({
        compress: true,
        mangle: true,
        global: true,
        sourcemap: false
      }, 'uglifyify');

SyntaxError: Unexpected token: operator (>) while parsing file: /Library/WebServer/Documents/doctor-app/node_modules/retrying-promise/lib/index.js

**Comment by wouter-vdb** [comment]
Enable ES6 mode.
